version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "postcode-lookup"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1uw1g3xyoa4jn"
s3_prefix = "postcode-lookup"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\" OsApiKey=\"mGvGWUtOi5aRYpACv6PyiofCOPkNOhPG\""

